spring:
  application:
    name: zzhh-server-java

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zeng?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: zzz000
    type: com.alibaba.druid.pool.DruidDataSource

  # email
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: zenghaifenghandsom@163.com
    password: ERUBMZGVGOOLSGCN
    port: 25
    properties:
      mail:
      smtp:
      auth: true
      socketFactory:
      class: javax.net.ssl.SSLSocketFactory
  # jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:

# mybatis plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

  # logic delete
  global-config:
    db-config:
      logic-delete-value: 1 # logic deleted value (default 1)
      logic-not-delete-value: 0 # logic not delete value (default 0)
server:
  port: 9000

# oss configure
alioss:
  acessKeyId:
  accessKeySecret:
  bucketName:

